match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 150
use_small_heuristics = "Max"

# Unstable features below
unstable_features = true
blank_lines_upper_bound = 5
enum_discrim_align_threshold = 5
struct_field_align_threshold = 5
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = false
group_imports = "StdExternalCrate"
version = "Two"
